In [1]:
# numpy used to work with arrays 
#https://youtu.be/CESPgl01b3c?feature=shared
import numpy as np

arr = np.array([1,2,3,4,5])

print(arr)
print(type(arr))


[1 2 3 4 5]
<class 'numpy.ndarray'>


In [6]:
import numpy as np

arr = np.array((1,2,3,4,5))
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
# 2D array

twoDArray = [[1,2,3],[4,5,6]]
import numpy as np

arr = np.array(twoDArray)
print(arr)

[[1 2 3]
 [4 5 6]]


In [17]:
# 3D array
# here depth is just 1
threeDArray = [[[1,2,3],[4,5,6]]]
import numpy as np

arr = np.array(threeDArray)
print(arr)
print("dimension of the matrix:",arr.ndim)

[[[1 2 3]
  [4 5 6]]]
dimension of the matrix: 3


In [ ]:
# defining dimension 

import numpy as np
list_ = [1,2,3]

arr = np.array(list_,ndmin=5)
print(arr)
print("dimension of the matrix:",arr.ndim)

[[[[[1 2 3]]]]]
dimension of the matrix: 5


NumPy Array Indexing



In [31]:

# arr[z][y][x]
import numpy as np
threeDArray = [[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]]

arr = np.array(threeDArray)

print(arr.ndim)
print("accessing z",arr[0])
print("accessing y",arr[0][0])  
print("accessing y",arr[0,0])   
print("accessing x",arr[0,0,0])  

3
accessing z [[1 2 3]
 [4 5 6]]
accessing y [1 2 3]
accessing y [1 2 3]
accessing x 1


Slicing 

In [42]:
# 1D slicing , 2D slicing , 3D Slcing 
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])
# 1D slicing
print(arr[1:4])  # Output: [2 3 4]

# 2D slicing 
arr = np.array([[1, 2, 3],[ 4, 5, 6]])
print(arr[0][0:2])


[2 3 4]
[1 2]


NumPy Data Types

In [48]:
# O- objects ( when u don't know which datatype your array consit)   
import numpy as np 
arr = np.array(["apple",1,3.2])
# here numpy covert all data type into string there form index 1 and 2 contactinate
print(arr[1]+arr[2])
print(arr.dtype) # output: object
 

13.2
<U32


In [ ]:
# O- objects ( when u don't know which datatype your array consit)   
import numpy as np 
arr = np.array([2,1,3.2])
# here numpy covert all data type into float datatype
print(arr[1]+arr[2])
print(arr.dtype) # output: object
 

4.2
float64


In [3]:
# Self created data type

# O- objects ( when u don't know which datatype your array consit )   
import numpy as np 
arr = np.array([2,1,3.2],dtype="i")  # here i have used int data type
# here numpy covert all data type into float datatype
print(arr[1]+arr[2])
print(arr.dtype) # output: object
 

4
int32


NumPy Array Copy vs View

In [ ]:
# View

import numpy as np

arr = np.array([1,2,3])
arr1 = arr.mean()
print(arr1)  # Output: [4 2 3]
print(arr)  # Output: [4 2 3]

2.0
[1 2 3]


In [ ]:
# here w was checkign that list not creating copy it's chagne teh exact list 
list_ = ["shubham",1,2,2.3]
list_[0] = "M"
print(list_)

['M', 1, 2, 2.3]


In [68]:
list1 = list_

In [72]:
list1[0]= "pawan"
print(list1)
print(list_)

['pawan', 1, 2, 2.3]
['pawan', 1, 2, 2.3]


In [ ]:
# view 
import numpy as np 
arr = np.array([1,2,3,4])
x = arr
x[0]=6465
print(x.dtype)
print(x)

int64
[6465    2    3    4]


In [ ]:
# assigment opeartor vs view 
# if u use = assimgent opetor than u create same object but in view u createing a new object with same data 4


In [ ]:
# view 
import numpy as np 
arr = np.array([1,2,3,4])
x = arr.copy()
y = arr.view()    # always remember base is here paramerte of arr not any methode( function )
print(x.base)
print(y.base)

None
[1 2 3 4]


Numpy Shape


In [ ]:
# x repreent column ,y represnt row and z represent depth
# (z,y,x) in this way u will see matrix
import numpy as np 
arr = np.array([[[1,2,3,4]]])
print(arr.shape)

(1, 1, 4)


Reshaping arrays


In [20]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

print("arr shape",arr.shape)
print("arr dime",arr.ndim)

newarr = arr.reshape(4,3)
print(newarr)
print("arr dime",newarr.ndim)

print("arr shape",newarr.shape)


arr shape (12,)
arr dime 1
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
arr dime 2
arr shape (4, 3)


In [ ]:
# Can We Reshape Into any Shape?
# yes as long as it's in equal in size in all
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

# let's shape this as u can see there is 8 element 
# reshpae into 3 x 3 matrix 3 rows and 3 column
arr = arr.reshape(3, 3)
# because we need 9 element to reshape into 3 x 3 matrix


ValueError: cannot reshape array of size 8 into shape (3,3)

In [25]:
# when we reshape the arry then that arry is copy or view 
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8,9])

newarr= arr.reshape(3,3)

print(newarr.base)  



[1 2 3 4 5 6 7 8 9]


In [ ]:
# Unknown Dimension

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

arr.reshape(2,-1) # here two row 4 coloumn




array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

arr.reshape(1,2,-1) # here two row 4 coloumn 1 depth



array([[[1, 2, 3, 4],
        [5, 6, 7, 8]]])

In [ ]:
# Flattening the arrays
# coverting any dim into 1 D

import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

newarr = arr.reshape(-1)

print(newarr)

[1 2 3 4 5 6]


In [35]:
# Iterating Arrays Using nditer()
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

for i in np.nditer(arr):
    print(i)

1
2
3
4
5
6


In [ ]:
    # Iterating Array With Different Data Types
# what is buffer ?
# tem memrory location is called buffer for holding temp data
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

# now u want diffeent datatype 


In [ ]:
import numpy as np

arr = np.array([[1, 2, 3], [46546464646676165761676467615, 5, 6]])  # so this numnber is to large to interate 

for i in np.nditer(arr, flags=['buffered'],op_dtypes=['S']):
    print(i.dtype)

TypeError: Iterator operand or requested dtype holds references, but the NPY_ITER_REFS_OK flag was not enabled

In [47]:
# Iterating With Different Step Size

import numpy as np

arr = np.array([[1, 2, 3], [2, 5, 6]])  # so this numnber is to large to interate 

for i in np.nditer(arr[:,::2]):
    print(i)

1
3
2
6


In [52]:
# Enumerated Iteration Using ndenumerate()
# when u want correnpoding index with 
import numpy as np

arr = np.array([[1, 2, 3], [2, 5, 6]])  # 

for i in np.ndenumerate(arr):
    print(i[0])
 

(0, 0)
(0, 1)
(0, 2)
(1, 0)
(1, 1)
(1, 2)


In [53]:
# Enumerated Iteration Using ndenumerate()
# when u want correnpoding index with 
import numpy as np

arr = np.array([[[1, 2, 3], [2, 5, 6]]])  # 

for i in np.ndenumerate(arr):
    print(i[0])

(0, 0, 0)
(0, 0, 1)
(0, 0, 2)
(0, 1, 0)
(0, 1, 1)
(0, 1, 2)


NumPy Joining Array


In [6]:
# Joining NumPy Arrays
# join == contactinate 
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr1 + arr2

# like this not worked as we doing in list

array([5, 7, 9])

In [3]:
l1= [1, 2, 3]

l2 =[4, 1, 6]

l1 + l2

[1, 2, 3, 4, 1, 6]

In [36]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate([arr1,arr2],axis=0)

print(arr)

[1 2 3 4 5 6]


In [37]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate([arr1,arr2],axis=1)

print(arr)

AxisError: axis 1 is out of bounds for array of dimension 1

In [39]:
import numpy as np

arr1 = np.array([[1, 2, 3]])

arr2 = np.array([[4, 5, 6]])

arr = np.concatenate([arr1,arr2],axis=0)

print(arr)

[[1 2 3]
 [4 5 6]]


In [40]:
import numpy as np

arr1 = np.array([[1, 2, 3]])

arr2 = np.array([[4, 5, 6]])

arr = np.stack([arr1,arr2],axis=0)

print(arr)

[[[1 2 3]]

 [[4 5 6]]]


In [41]:
import numpy as np

arr1 = np.array([[1, 2, 3]])

arr2 = np.array([[4, 5, 6]])

arr = np.stack([arr1,arr2],axis=1)

print(arr)

[[[1 2 3]
  [4 5 6]]]


In [ ]:
# Joining Using Stack Function 

# why we r using stack function :
# => Contactinate joined array in same axis but stack but stack  add additional axis to join it.
 
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.stack([arr1,arr2],axis=0)  # axis = 0 means join along rows

print(arr)

[[1 2 3]
 [4 5 6]]


In [16]:

import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.stack([arr1,arr2],axis=1)  # axis = 1 means join along columns
print(arr)

[[1 4]
 [2 5]
 [3 6]]


In [20]:
# h stack and v stack

import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])


arr = np.hstack([arr1,arr2])
print(arr)




[1 2 3 4 5 6]


In [26]:
import numpy as np

arr1 = np.array([[1, 2, 3],[4,5,6]])

arr2 = np.array([["a","b","c"],["d","e","f"]])

arr = np.hstack([arr1,arr2])
print(arr.shape)
print(arr)

(2, 6)
[['1' '2' '3' 'a' 'b' 'c']
 ['4' '5' '6' 'd' 'e' 'f']]


In [34]:
list_ = [['1', '2' ,'3' ,'a' ,'b' ,'c'],
        ['4' ,'5' ,'6', 'd', 'e' ,'f']]

arr = np.array(list_)
print(arr)

[['1' '2' '3' 'a' 'b' 'c']
 ['4' '5' '6' 'd' 'e' 'f']]


In [19]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.vstack([arr1,arr2])
print(arr)

[[1 2 3]
 [4 5 6]]


In [21]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.dstack((arr1, arr2))

print(arr)

[[[1 4]
  [2 5]
  [3 6]]]


In [43]:
# Spliting array 

# 1 D array 
import numpy as np

arr1 = np.array([1, 2, 3])

arr = np.array_split(arr1,2)

print(arr)

[array([1, 2]), array([3])]


In [45]:
# Splitting 2-D Arrays

import numpy as np

arr1 = np.array([[1, 2, 3],[4,5,6]])

arr = np.array_split(arr1,2)

print(arr)

[array([[1, 2, 3]]), array([[4, 5, 6]])]


In [51]:
# you can say that on which axis you want to split array 

  # axis = 1 means split  along columns
  
import numpy as np


arr1 = np.array([1, 2, 3])


arr = np.array_split(arr1,3,axis=0)

print(arr)

[array([1]), array([2]), array([3])]


In [58]:
import numpy as np


arr1 = np.array([1, 2, 3])


arr = np.array_split(arr1,3,axis=1)
print(arr)

IndexError: tuple index out of range

In [59]:
arr2d = np.array([[1, 2, 3],
                [4, 5, 6]])
print(arr2d.shape)  # (1, 3)

split = np.array_split(arr2d, 3, axis=1)
print(split)


(2, 3)
[array([[1],
       [4]]), array([[2],
       [5]]), array([[3],
       [6]])]


In [55]:
# you can say that on which axis you want to split array 

  # axis = 1 means split  along columns
  
import numpy as np


arr1 = np.array([[1, 2, 3]])


arr = np.array_split(arr1,3,axis=1)

print(arr[0],arr[1])

[[1]] [[2]]


In [57]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3, axis=1)

print(newarr[0])

[[ 1]
 [ 4]
 [ 7]
 [10]
 [13]
 [16]]


In [ ]:
import numpy as np

arr1 = np.array([[1,2,3,4]])

arr = np.split(arr1,2,axis=1)
print(arr)

[array([[1, 2]]), array([[3, 4]])]


clearing every concept of stacking , spliiting after chaning axes 

In [ ]:
import numpy as np

# 1 D 
# stacking 

arr1 = np.array([1,2,3])

arr2 = np.array([4,5,6])

# stacking create a new dim becuase it's create a new axis
# axis =0 means : along column
# axis = 1 means: along rows


# so when i say axis = 0 then my mean to say that : stack alogn vertically which will create row type data

# when  i say x =1 then stack along horizontally which will crate column type data

arr = np.stack([arr1,arr2],axis=0)

print(arr)

# output: [[1,2,3][4,5,6]]

# because it's creating a nex axis y and contactinate it 





[[1 2 3]
 [4 5 6]]


In [ ]:
# when we say stac along horizontally we say axis = 1
arr1 = np.array([1,2,3])

arr2 = np.array([4,5,6])

arr = np.stack([arr1,arr2],axis=1)
print(arr) # output shape (3,2)  # 3 rows and 2 column

[[1 4]
 [2 5]
 [3 6]]


In [13]:
arr1 = np.array([1,2,3])

arr2 = np.array([4,5,6])

arr = np.vstack([arr1,arr2])
print(arr) 
arr = np.hstack([arr1,arr2])
print(arr) 

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [ ]:
# Example
# Student Exam Scores
# let's take 3 students took 2 different test and their score is like
#[85, 90, 78]  <- test 1
#[88, 92, 80]  <- test 2


# perfomance 
# 1. calculate the average score of each student

import numpy as np

test1_score = np.array([85, 90, 78])
test2_score = np.array([88, 92, 80])


arr = np.stack([test1_score,test2_score],axis=0)

avg_score = arr.mean()

np_avg_score = np.average(arr,axis=0) # avg score of each studetn in test 1 and test 2 
# 
print(arr)
print(avg_score)
print(np_avg_score)


[[85 90 78]
 [88 92 80]]
85.5
[86.5 91.  79. ]


Searching an array

In [7]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 4, 4])


x = np.where(arr==4)  # value four present at index 3, 5, 6
print(x)

(array([3, 5, 6]),)


In [ ]:
# opeation finding 
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr%2 == 0) # this will give us the elements index which is even

print(x)  # this will


(array([1, 3, 5, 6]),)


Search Sorted


In [19]:
# What is binary serach:
# it's search value by making every time list half.


# Search Sorted will return u index from the sorted list where u place new element the still to be sorted


import numpy as np


arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr,7)

print(x)

1


In [ ]:

# by defult left value return but u can change right 
import numpy as np

arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7, side='right')

print(x)

2


In [23]:
# searching multiple value

import numpy as np

arr = np.array([1, 3, 5, 7])

x=np.searchsorted(arr,[3,4,5,8])

print(x)

[1 2 2 4]


In [26]:
# numpy sorting 


import numpy as np

arr = np.array([1, 3, 8, 7])

x = np.sort(arr)

print(x)

[1 3 7 8]


In [ ]:
#Sorting a 2-D Array



import numpy as np 

arr = np.array([[4,8,6],[1,5,3]])

x = np.sort(arr)

print(x) # so it's sort both array


[[4 6 8]
 [1 3 5]]


NumPy Filter Array


In [ ]:
# filtering array: measn fitler data which meets condition 

import numpy as np

arr = np.array([10, 20, 30, 40, 50])


condition = arr > 23
print(condition) #[False False  True  True  True]

x = arr[condition] # [30 40 50]

print(x)

[False False  True  True  True]
[30 40 50]


In [38]:
import numpy as np

arr = np.array([[10, 20, 30, 40, 50],[34,343,3534,343,232]])


condition = arr > 23
print(condition) #[False False  True  True  True]

x = arr[condition] # [30 40 50]

print(x)

[[False False  True  True  True]
 [ True  True  True  True  True]]
[  30   40   50   34  343 3534  343  232]
