In [ ]:
# numpy used to work with arrays 
#https://youtu.be/CESPgl01b3c?feature=shared
import numpy as np

arr = np.array([1,2,3,4,5])

print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [6]:
import numpy as np

arr = np.array((1,2,3,4,5))
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
# 2D array

twoDArray = [[1,2,3],[4,5,6]]
import numpy as np

arr = np.array(twoDArray)
print(arr)

[[1 2 3]
 [4 5 6]]


In [17]:
# 3D array
# here depth is just 1
threeDArray = [[[1,2,3],[4,5,6]]]
import numpy as np

arr = np.array(threeDArray)
print(arr)
print("dimension of the matrix:",arr.ndim)

[[[1 2 3]
  [4 5 6]]]
dimension of the matrix: 3


In [ ]:
# defining dimension 

import numpy as np
list_ = [1,2,3]

arr = np.array(list_,ndmin=5)
print(arr)
print("dimension of the matrix:",arr.ndim)

[[[[[1 2 3]]]]]
dimension of the matrix: 5


NumPy Array Indexing



In [ ]:

# arr[z][y][x]
import numpy as np
threeDArray = [[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]]

arr = np.array(threeDArray)

print(arr.ndim)
print(arr[0])  

3
[[1 2 3]
 [4 5 6]]
