In [1]:
# numpy used to work with arrays 
#https://youtu.be/CESPgl01b3c?feature=shared
import numpy as np

arr = np.array([1,2,3,4,5])

print(arr)
print(type(arr))


[1 2 3 4 5]
<class 'numpy.ndarray'>


In [6]:
import numpy as np

arr = np.array((1,2,3,4,5))
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
# 2D array

twoDArray = [[1,2,3],[4,5,6]]
import numpy as np

arr = np.array(twoDArray)
print(arr)

[[1 2 3]
 [4 5 6]]


In [17]:
# 3D array
# here depth is just 1
threeDArray = [[[1,2,3],[4,5,6]]]
import numpy as np

arr = np.array(threeDArray)
print(arr)
print("dimension of the matrix:",arr.ndim)

[[[1 2 3]
  [4 5 6]]]
dimension of the matrix: 3


In [ ]:
# defining dimension 

import numpy as np
list_ = [1,2,3]

arr = np.array(list_,ndmin=5)
print(arr)
print("dimension of the matrix:",arr.ndim)

[[[[[1 2 3]]]]]
dimension of the matrix: 5


NumPy Array Indexing



In [31]:

# arr[z][y][x]
import numpy as np
threeDArray = [[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]]

arr = np.array(threeDArray)

print(arr.ndim)
print("accessing z",arr[0])
print("accessing y",arr[0][0])  
print("accessing y",arr[0,0])   
print("accessing x",arr[0,0,0])  

3
accessing z [[1 2 3]
 [4 5 6]]
accessing y [1 2 3]
accessing y [1 2 3]
accessing x 1


Slicing 

In [42]:
# 1D slicing , 2D slicing , 3D Slcing 
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])
# 1D slicing
print(arr[1:4])  # Output: [2 3 4]

# 2D slicing 
arr = np.array([[1, 2, 3],[ 4, 5, 6]])
print(arr[0][0:2])


[2 3 4]
[1 2]


NumPy Data Types

In [48]:
# O- objects ( when u don't know which datatype your array consit)   
import numpy as np 
arr = np.array(["apple",1,3.2])
# here numpy covert all data type into string there form index 1 and 2 contactinate
print(arr[1]+arr[2])
print(arr.dtype) # output: object
 

13.2
<U32


In [ ]:
# O- objects ( when u don't know which datatype your array consit)   
import numpy as np 
arr = np.array([2,1,3.2])
# here numpy covert all data type into float datatype
print(arr[1]+arr[2])
print(arr.dtype) # output: object
 

4.2
float64


In [3]:
# Self created data type

# O- objects ( when u don't know which datatype your array consit )   
import numpy as np 
arr = np.array([2,1,3.2],dtype="i")  # here i have used int data type
# here numpy covert all data type into float datatype
print(arr[1]+arr[2])
print(arr.dtype) # output: object
 

4
int32


NumPy Array Copy vs View

In [ ]:
# View

import numpy as np

arr = np.array([1,2,3])
arr1 = arr.mean()
print(arr1)  # Output: [4 2 3]
print(arr)  # Output: [4 2 3]

2.0
[1 2 3]


In [ ]:
# here w was checkign that list not creating copy it's chagne teh exact list 
list_ = ["shubham",1,2,2.3]
list_[0] = "M"
print(list_)

['M', 1, 2, 2.3]


In [68]:
list1 = list_

In [72]:
list1[0]= "pawan"
print(list1)
print(list_)

['pawan', 1, 2, 2.3]
['pawan', 1, 2, 2.3]


In [ ]:
# view 
import numpy as np 
arr = np.array([1,2,3,4])
x = arr
x[0]=6465
print(x.dtype)
print(x)

int64
[6465    2    3    4]


In [ ]:
# assigment opeartor vs view 
# if u use = assimgent opetor than u create same object but in view u createing a new object with same data 4


In [ ]:
# view 
import numpy as np 
arr = np.array([1,2,3,4])
x = arr.copy()
y = arr.view()    # always remember base is here paramerte of arr not any methode( function )
print(x.base)
print(y.base)

None
[1 2 3 4]


Numpy Shape


In [ ]:
# x repreent column ,y represnt row and z represent depth
# (z,y,x) in this way u will see matrix
import numpy as np 
arr = np.array([[[1,2,3,4]]])
print(arr.shape)

(1, 1, 4)


Reshaping arrays


In [20]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

print("arr shape",arr.shape)
print("arr dime",arr.ndim)

newarr = arr.reshape(4,3)
print(newarr)
print("arr dime",newarr.ndim)

print("arr shape",newarr.shape)


arr shape (12,)
arr dime 1
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
arr dime 2
arr shape (4, 3)


In [ ]:
# Can We Reshape Into any Shape?
# yes as long as it's in equal in size in all
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

# let's shape this as u can see there is 8 element 
# reshpae into 3 x 3 matrix 3 rows and 3 column
arr = arr.reshape(3, 3)
# because we need 9 element to reshape into 3 x 3 matrix


ValueError: cannot reshape array of size 8 into shape (3,3)

In [25]:
# when we reshape the arry then that arry is copy or view 
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8,9])

newarr= arr.reshape(3,3)

print(newarr.base)  



[1 2 3 4 5 6 7 8 9]


In [ ]:
# Unknown Dimension

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

arr.reshape(2,-1) # here two row 4 coloumn




array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

arr.reshape(1,2,-1) # here two row 4 coloumn 1 depth



array([[[1, 2, 3, 4],
        [5, 6, 7, 8]]])

In [ ]:
# Flattening the arrays
# coverting any dim into 1 D

import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

newarr = arr.reshape(-1)

print(newarr)

[1 2 3 4 5 6]


In [35]:
# Iterating Arrays Using nditer()
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

for i in np.nditer(arr):
    print(i)

1
2
3
4
5
6


In [ ]:
    # Iterating Array With Different Data Types
# what is buffer ?
# tem memrory location is called buffer for holding temp data
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

# now u want diffeent datatype 


In [ ]:
import numpy as np

arr = np.array([[1, 2, 3], [46546464646676165761676467615, 5, 6]])  # so this numnber is to large to interate 

for i in np.nditer(arr, flags=['buffered'],op_dtypes=['S']):
    print(i.dtype)

TypeError: Iterator operand or requested dtype holds references, but the NPY_ITER_REFS_OK flag was not enabled

In [47]:
# Iterating With Different Step Size

import numpy as np

arr = np.array([[1, 2, 3], [2, 5, 6]])  # so this numnber is to large to interate 

for i in np.nditer(arr[:,::2]):
    print(i)

1
3
2
6


In [52]:
# Enumerated Iteration Using ndenumerate()
# when u want correnpoding index with 
import numpy as np

arr = np.array([[1, 2, 3], [2, 5, 6]])  # 

for i in np.ndenumerate(arr):
    print(i[0])
 

(0, 0)
(0, 1)
(0, 2)
(1, 0)
(1, 1)
(1, 2)


In [53]:
# Enumerated Iteration Using ndenumerate()
# when u want correnpoding index with 
import numpy as np

arr = np.array([[[1, 2, 3], [2, 5, 6]]])  # 

for i in np.ndenumerate(arr):
    print(i[0])

(0, 0, 0)
(0, 0, 1)
(0, 0, 2)
(0, 1, 0)
(0, 1, 1)
(0, 1, 2)


NumPy Joining Array


In [6]:
# Joining NumPy Arrays
# join == contactinate 
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr1 + arr2

# like this not worked as we doing in list

array([5, 7, 9])

In [3]:
l1= [1, 2, 3]

l2 =[4, 1, 6]

l1 + l2

[1, 2, 3, 4, 1, 6]

In [36]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate([arr1,arr2],axis=0)

print(arr)

[1 2 3 4 5 6]


In [37]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate([arr1,arr2],axis=1)

print(arr)

AxisError: axis 1 is out of bounds for array of dimension 1

In [39]:
import numpy as np

arr1 = np.array([[1, 2, 3]])

arr2 = np.array([[4, 5, 6]])

arr = np.concatenate([arr1,arr2],axis=0)

print(arr)

[[1 2 3]
 [4 5 6]]


In [40]:
import numpy as np

arr1 = np.array([[1, 2, 3]])

arr2 = np.array([[4, 5, 6]])

arr = np.stack([arr1,arr2],axis=0)

print(arr)

[[[1 2 3]]

 [[4 5 6]]]


In [41]:
import numpy as np

arr1 = np.array([[1, 2, 3]])

arr2 = np.array([[4, 5, 6]])

arr = np.stack([arr1,arr2],axis=1)

print(arr)

[[[1 2 3]
  [4 5 6]]]


In [ ]:
# Joining Using Stack Function 

# why we r using stack function :
# => Contactinate joined array in same axis but stack but stack  add additional axis to join it.
 
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.stack([arr1,arr2],axis=0)  # axis = 0 means join along rows

print(arr)

[[1 2 3]
 [4 5 6]]


In [16]:

import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.stack([arr1,arr2],axis=1)  # axis = 1 means join along columns
print(arr)

[[1 4]
 [2 5]
 [3 6]]


In [20]:
# h stack and v stack

import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])


arr = np.hstack([arr1,arr2])
print(arr)




[1 2 3 4 5 6]


In [26]:
import numpy as np

arr1 = np.array([[1, 2, 3],[4,5,6]])

arr2 = np.array([["a","b","c"],["d","e","f"]])

arr = np.hstack([arr1,arr2])
print(arr.shape)
print(arr)

(2, 6)
[['1' '2' '3' 'a' 'b' 'c']
 ['4' '5' '6' 'd' 'e' 'f']]


In [34]:
list_ = [['1', '2' ,'3' ,'a' ,'b' ,'c'],
        ['4' ,'5' ,'6', 'd', 'e' ,'f']]

arr = np.array(list_)
print(arr)

[['1' '2' '3' 'a' 'b' 'c']
 ['4' '5' '6' 'd' 'e' 'f']]


In [19]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.vstack([arr1,arr2])
print(arr)

[[1 2 3]
 [4 5 6]]


In [21]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.dstack((arr1, arr2))

print(arr)

[[[1 4]
  [2 5]
  [3 6]]]
